### ISSUE TITLE
Changing language

### ISSUE THREAD

**Issue by PYL29** [sergiosolorzano/TalkomicApp-Unity#1]
Hello! Is there a hardcoded setting for changing the language? I don't want to have a multilanguage app but i need to change the language. Is there any way to do that?

**Comment by sergiosolorzano** [comment]
Hi @PYL29 there isn't. The whisper model for this prototype repo is configured for whisper-tiny.en english-only and is converted to [onnx format](https://tapgaze.com/blog/podcast-to-image-slider/#whisper-olive), I think you'd need a multilingual model. Also please note [multilingual support ](https://github.com/microsoft/Olive/blob/main/examples/whisper/README.md)requires onnxruntime>=1.16.0

**Comment by PYL29** [comment]
Thanks for answering!
