### ISSUE TITLE
Has this project been tested on iOS devices ?

### ISSUE THREAD

**Issue by shubham-kumar-ucentrics** [sergiosolorzano/TalkomicApp-Unity#2]

**Comment by sergiosolorzano** [comment]
Hello @shubham-kumar-ucentrics  it hasn't, nope, only win11. I can guess a mobile device would probably struggle as whisper and diffusion on U-Net run locally and these made good use of the hardware when run on win11 - see tested environment on the "Prototype" section of the README https://github.com/sergiosolorzano/TalkomicApp-Unity#prototype-software

**Comment by sergiosolorzano** [comment]
Closing issue as stale, please re-open if you need help
